{% set name = "gwdetchar" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3be2d05e8459aec336e853409f5a077f0d4f996ea753853fce4009705223c281

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - jsmin
    - libsass
    - pip
    - python
    - setuptools
  run:
    - python >=3.5
    - astropy >=1.2
    - beautifulsoup4
    - gwdatafind
    - gwpy >=0.13.0
    - gwtrigfind
    - lxml
    - markuppy >=1.14
    - matplotlib >=2.0.0
    - numpy >=1.10
    - pandas
    - pathlib2  # [py<36]
    - pycondor
    - pytz
    - coloredlogs
    - pygments
    - python-ldas-tools-framecpp
    - scikit-learn
    - scipy >=1.2.0
    - setuptools

test:
  requires:
    - flake8
    - pytest
    - coverage
  imports:
    - gwdetchar
    - gwdetchar.cds
    - gwdetchar.cli
    - gwdetchar.condor
    - gwdetchar.const
    - gwdetchar.daq
    - gwdetchar.io
    - gwdetchar.io.html
    - gwdetchar.io.datafind
    - gwdetchar.io.tests
    - gwdetchar.lasso
    - gwdetchar.lasso.plot
    - gwdetchar.lasso.tests
    - gwdetchar.plot
    - gwdetchar.omega
    - gwdetchar.omega.plot
    - gwdetchar.omega.html
    - gwdetchar.omega.config
    - gwdetchar.omega.tests
    - gwdetchar.saturation
    - gwdetchar.scattering
    - gwdetchar.scattering.plot
    - gwdetchar.scattering.tests
    - gwdetchar.tests
    - gwdetchar.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check scripts run ok
    - gwdetchar-lasso-correlation --help
    - gwdetchar-mct --help
    - gwdetchar-omega --help
    - gwdetchar-omega-batch --help
    - gwdetchar-overflow --help
    - gwdetchar-scattering --help
    - python -m gwdetchar.scattering --help
    - gwdetchar-slow-correlation --help
    - gwdetchar-software-saturations --help
    - python -m gwdetchar.nagios --help

about:
  home: https://gwdetchar.readthedocs.io
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A python package for gravitational-wave detector characterisation
  description: |
    This package provides a set of python utilities for gravitational-wave
    detector characterisation and data quality.

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
