travis:
  secure:
    BINSTAR_TOKEN: O4qddVUBqr/+pQwvRLf6bzHypXNNRSoc39qgAyy4LagUXTeKnWV00ppbBNZ46B025wBWqicBxhNHpUZXFaOrwqFrYBoYvZAt55Kj81KmPMWCExqpLFAmoilRmsdnFfZZRGzGmuGsGRc3iUeqCui/6KopgIMd1TkzCQ9JPSNEGjvNDWJ6MUkXophczSIPCJfX7cbMh6TusnCTaGeRYQspuoq276k358Chm6LYs93s+nWMhr8T2LthktnomoNA1539FyQNOb22V47umkcdIP6zuZaOrOORDabAeiyCBZEwSio4WiUm/plXN6YABo38Y6orVCsZEpSuEjBtRhpXS79gDjkE+e2IrLoi87/NhIbLfql3v7DNKzan5merd9bgZyv5MxUxUYvv/363mptEEn1Y9pgPSdWELTKS+RnJEZLJceIxRlkMqRz06JwywpFeIySVezOdxTCJsC/MfYOSo1ZFgrMdZu4XRL833cEe4hxgpnpgaRF4n8NHlCABz+iFNkip1lOWTjl8MbAX0Y6tISHIyRGI/T+1FNaNE7v0HUyEN0uTCCo2L1SES2szrMiBP8wynNXtWk59x3ZGa5iIGyBS7bvANQ6mQRhy2Ne+aqmHpYcj556klTFQc3ox/cHRcSi4UC4WkdcjqgpweVdU5foj06+EEfoSX2du1FuVcAtZA7A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
